_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 77
            "2":
                - 1
                - 11
                - 49
                - 55
                - 77
            "3":
                - 1
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.2
            "5": 0.19.0
            "6": 4.41.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
