#model_name
model_name : FNO #, UNO , TFNO , PINO_darcy

#parameters
in_channels : 1
out_channels : 1
hidden_channels : 32
projection_channel_ratio : 2
modes : 12

#training
epochs : 100
lr : 0.001
optimizer : Adam
scheduler : False
step_size : 100
gamma : 0.1


#gpu
device : 'cpu'



#tracking 
wandb_logs : False
save_version : 0
