#model_name
model_name : 1D_PINNmodel

#parameters
N_input : 1
N_hidden : 100  
N_layers : 2
N_output : 1

#training
epochs : 10
lr : 0.001


#pde parameters
TF : False
weight : 1
adaptive_nodes : 0
update_rate : 100
bound_left : 1
bound_right : -1



#tracking 
wandb_logs : False
