N_hidden: 100
N_input: 2
N_layers: 2
N_output: 1
TF: true
adaptive_nodes: 0
bound_left: 1
epochs: 10000
lr: 0.01
model_name: 2D_PINNmodel
save_version: 1
update_rate: 500
wandb_logs: false
weight: 1.0
